// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCV9koWPuH95itU4qsFTlAqaDoAnrVqtfU',
    appId: '1:917963014037:web:8ae9929dfbc1131f9d809c',
    messagingSenderId: '917963014037',
    projectId: 'cow-dairy-system',
    authDomain: 'cow-dairy-system.firebaseapp.com',
    storageBucket: 'cow-dairy-system.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcAGfuVX5Rdkl6H31AMluq9TdlKdMz22c',
    appId: '1:917963014037:android:82a230700b14a25e9d809c',
    messagingSenderId: '917963014037',
    projectId: 'cow-dairy-system',
    storageBucket: 'cow-dairy-system.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbLV3l7zOi2N1qkztnC8hzl0FBqy8aBKI',
    appId: '1:917963014037:ios:95deeb883900b0d39d809c',
    messagingSenderId: '917963014037',
    projectId: 'cow-dairy-system',
    storageBucket: 'cow-dairy-system.appspot.com',
    iosClientId: '917963014037-2bcterl2g59kd6hcbam93lgeim9jj8gb.apps.googleusercontent.com',
    iosBundleId: 'com.SamTech.khanDairy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbLV3l7zOi2N1qkztnC8hzl0FBqy8aBKI',
    appId: '1:917963014037:ios:95deeb883900b0d39d809c',
    messagingSenderId: '917963014037',
    projectId: 'cow-dairy-system',
    storageBucket: 'cow-dairy-system.appspot.com',
    iosClientId: '917963014037-2bcterl2g59kd6hcbam93lgeim9jj8gb.apps.googleusercontent.com',
    iosBundleId: 'com.SamTech.khanDairy',
  );
}
